const data_test = [{
    'id': 3593,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL38020M7',
    'name': 'ThinkPad L380 Yoga',
    'price': 108540.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l380-yoga-series-front.png?context=bWFzdGVyfHJvb3R8MjU1MDN8aW1hZ2UvcG5nfGgyYS9oZDIvOTYzMzMzMTkwNDU0Mi5wbmd8OTAxOTVlM2ExNjdmMzUyZjkzNzRkOTBhYjE3ZGFmNjMwNGFjZjgzODBhODE2YTM5YWMyMGM0NzM4ZjRmYjU1NQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L380-Yoga/p/22TP2TBL38020M7',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型マルチモードPC</strong><br /><ul><li>利用シーンにあわせてモードを変更</li><li>安心のセキュリティ</li></ul>'
}, {
    'id': 3594,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL38020M5',
    'name': 'ThinkPad L380',
    'price': 64233.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l380-series-front.png?context=bWFzdGVyfHJvb3R8MTk5Njl8aW1hZ2UvcG5nfGhhMC9oY2EvOTYzMzMzMDU5MzgyMi5wbmd8NjZkYzE0OWMxN2NhNjMwMDc2YTQ1NjMyZWMyYTU4YWE4MTcwYzNlMjVjYTA4NTljYzA2NTY2YjY0YzA4NWU2OA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L380/p/22TP2TBL38020M5',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型ビジネスPC</strong> <ul><li>優れたコストパフォーマンス</li><li>安心のセキュリティ</li></ul>'
}, {
    'id': 3595,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL480',
    'name': 'ThinkPad L480',
    'price': 87885.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l480-series-front.png?context=bWFzdGVyfHJvb3R8MjA4MjV8aW1hZ2UvcG5nfGg0NS9oMmEvOTYwOTE4NDgzNzY2Mi5wbmd8YTFkYzYzNmZlZjJkN2I4Nzk3MjYxZDExMmJlMmQwNGM0M2ViYWFlN2M2YjY5NmRmZDRkMjY0NzkxZWM3NzYyMw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L480/p/22TP2TBL480',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型ビジネスノートPC</strong> <ul><li>ビジネスの生産性を高める高性能</li><li>強化されたセキュリティ</li></ul>'
}, {
    'id': 3596,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL580',
    'name': 'ThinkPad L580',
    'price': 85860.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l580-series-front.png?context=bWFzdGVyfHJvb3R8MjMxOTF8aW1hZ2UvcG5nfGgzMy9oYWYvOTYwOTE4NjU0MTU5OC5wbmd8YTljN2I3Y2E5ZDc1ODI0MDljZmFiN2JmYjk2MjAwNzU2ODFkMTg5MGNiMjU1ZTEzNGI4YjQ3OTVlM2VjM2E0NA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L580/p/22TP2TBL580',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型ビジネスノートPC</strong> <ul><li>ビジネスの生産性を高める高性能</li><li>強化されたセキュリティ</li></ul>'
}, {
    'id': 3597,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL470',
    'name': 'ThinkPad L470',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l470-400x300.png?context=bWFzdGVyfGltYWdlc3w2ODA0MnxpbWFnZS9wbmd8aW1hZ2VzL2g5Zi9oOWQvOTQwMzk0MjU2Nzk2Ni5wbmd8MDhmNGVlNWEyZWVmNWVkZmVjOTczOTY4NmE3MjA4NjNjOWM3YWFhMWZhMzNiYjI1OGViMjYzYWJjNGRjM2RmNQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L470/p/22TP2TBL470',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 スタンダードノート</strong> <ul><li>高い堅牢性と信頼性</li><li>高く評価されているキーボード</li></ul>'
}, {
    'id': 3598,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL570',
    'name': 'ThinkPad L570',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l570-400x300.png?context=bWFzdGVyfHJvb3R8NzEyNzF8aW1hZ2UvcG5nfGg0My9oNGQvOTQwMzk0MzcxNDg0Ni5wbmd8ZDM4YTRjZTcwNGQ1ZDJjYzllZDk2OWFmYTAxZmRhNTk0ZTI0MTZkNGEwOGRmYjRlZjQ5ZWM3NzJlOGNlNjdhMQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/Thinkpad-L570/p/22TP2TBL570',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong> <ul><li>高い堅牢性と信頼性</li><li>高く評価されているキーボード</li></ul>'
}, {
    'id': 3599,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TBL560',
    'name': 'ThinkPad L560',
    'price': 54540.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-l560-front.png?context=bWFzdGVyfGltYWdlc3w2NDEwM3xpbWFnZS9wbmd8aW1hZ2VzL2hkNy9oM2YvOTMyNzE5MjQwODA5NC5wbmd8NWM3MWE3MTMwMDYwM2Y3NmZlZWJlMTBhNzdhZDI5Y2U1NzUxMDE0OGU1N2ZmODRjOTU2MDFmZTJmMmYwNmMwZQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/l-series/ThinkPad-L560/p/22TP2TBL560',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'l-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 スタンダードノート</b><br /><div>・高い堅牢性と信頼性</div><div>・高く評価されているキーボード</div>'
}, {
    'id': 3600,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP1000715',
    'name': 'Ideapad 110 (第7世代AMD搭載）',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-110-15-back.png?context=bWFzdGVyfGltYWdlc3wyNDU2NnxpbWFnZS9wbmd8aW1hZ2VzL2hiYS9oOWIvOTM5NzQ3ODI2MDc2Ni5wbmd8OGJlMTc4MjViOGEwMWU3ZmYyNzA5OGFmMmNlMzQ4M2IwODYyNzEzM2M3MWRhYmViN2IyMTA4YjAwNTk0ZDNhMQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/100-series/Ideapad-110-15-AMD/p/88IP1000715',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '100-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 エントリーノート</b><br />（量販店モデル）<br /><div><div>・AMDプロセッサー搭載</div><div>・優れたコストパフォーマンス</div></div>'
}, {
    'id': 3601,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP1000710',
    'name': 'Ideapad 110 (AMD搭載）',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-110-15-back.png?context=bWFzdGVyfGltYWdlc3wyNDU2NnxpbWFnZS9wbmd8aW1hZ2VzL2hkNS9oNWQvOTM0MDc3MTEzOTYxNC5wbmd8MzZlZGIzOTc5NzI2OWVjOGMzNTg2MzY2ZjFlZTNhYzU2YjgzNjhmMzM5MmRmZThlNmNmNmVmN2VlNDhlZmYyZg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/100-series/Ideapad-110-15-AMD/p/88IP1000710',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '100-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 エントリーノート</b><br />（量販店モデル）<br /><div>・AMDプロセッサー搭載</div><div>・優れたコストパフォーマンス</div>'
}, {
    'id': 3602,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88YG3000888',
    'name': 'Yoga 330',
    'price': 41900.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-yoga-330-11-front.png?context=bWFzdGVyfHJvb3R8MzEwNTh8aW1hZ2UvcG5nfGhhZS9oZGIvOTYzNTc5OTMwMjE3NC5wbmd8MzYzN2Q1MDAyYzg1ODQ3NDc0NjIyOWUwNjA4MDQ4MzI4NzY0YzllMmI2ZDM5OTE2YWYzNTA5ZmUzNjAyZWIwNQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-300-series/Yoga-330-11/p/88YG3000888',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-300-series',
    'date': '2018-05-27',
    'description': '<strong>軽量で使いやすい2-in-1ノート</strong><div><ul><li>どこへでも持ち運べる軽量ボディ</li><li>4つのモードで利用可能。</li><li>快適なパフォーマンスのインテル&reg; プロセッサー搭載</li></ul></div>'
}, {
    'id': 3603,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88YG3000595',
    'name': 'Yoga 300 ',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-yoga-300-11-back.png?context=bWFzdGVyfGltYWdlc3w1MTEwOXxpbWFnZS9wbmd8aW1hZ2VzL2hkOS9oMDAvOTMyNjgwNjcyODczNC5wbmd8YmY1MjQ2MzBkNTk0YThjNTQwZDcwMzhmM2QxZDc4M2QyMTlmNDEwN2ZkNTQ0NWZlMzFmMDk1YWE4Zjc3YTBkOA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-300-series/Yoga-300-11/p/88YG3000595',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-300-series',
    'date': '2018-05-27',
    'description': '<b>11.6型エントリーマルチモード</b><br /><div><div>・4つのモードでスタイル自由</div><div>・タッチパネルで直感的な操作</div></div>'
}, {
    'id': 3604,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88YG9000859',
    'name': 'Yoga 920',
    'price': 142301.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-yoga-920-front.png?context=bWFzdGVyfHJvb3R8MzE3MDV8aW1hZ2UvcG5nfGhkMS9oNzEvOTUwNTE1NDU5Njg5NC5wbmd8NTQzYzJjOTI5YzM0MTMwN2ExYmQwODUzODcyZDc2MTRhZmFmODNjZmNhZTdjN2UwY2I4MjdjMjUyMzhjMDgwNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-900-series/Yoga-920-13/p/88YG9000859',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-900-series',
    'date': '2018-05-27',
    'description': '<strong>13.9型プレミアムモバイル</strong><br />【レノボ・ショッピング限定販売】<ul><li>モードを切り替えてスタイル自由</li><li>狭いベゼルのスリムな液晶</li><li>高性能フラッグシップモデル</li></ul>'
}, {
    'id': 3605,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88YG9000786',
    'name': 'Yoga 910',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-yoga-910-13-gray-back.png?context=bWFzdGVyfGltYWdlc3wxODY4OHxpbWFnZS9wbmd8aW1hZ2VzL2hmZS9oY2YvOTM1NjEyNjA2MDU3NC5wbmd8ODBmMjljOGE2MGFhNDAxNjQ5NDdjNTU5NjQzOGQ5MTBlNjVmMDdiNmJiZjdiNmE2ZDg1M2NjNzdhMWE5ODhiNA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-900-series/Yoga-910/p/88YG9000786',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-900-series',
    'date': '2018-05-27',
    'description': '<strong>13.9型プレミアムモバイル</strong><ul><li>4つのモードでスタイル自由</li><li>スリムな狭額縁液晶</li><li>高性能フラッグシップモデル</li></ul>'
}, {
    'id': 3606,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP3001009',
    'name': '330',
    'price': 53033.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-330-14-front.png?context=bWFzdGVyfHJvb3R8MTk5NDJ8aW1hZ2UvcG5nfGhiNS9oNDYvOTcxMzM4NzMwNzAzOC5wbmd8Mjg5NGMzZTc4ZWZjMzhmNjZmMTVlNGNjYzcwOGJlYzkzY2Q4OWEzOGNmZTliYzAxMjJlMDllYTA0ZDQ3ZDQ0OA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300-series/Lenovo-ideapad-330-14IKB/p/88IP3001009',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300-series',
    'date': '2018-05-27',
    'description': '<strong>14型 スタンダードノート</strong><ul> <li>インテルプロセッサー搭載</li> <li>優れたパフォーマンス </li> <li>スタイリッシュなデザイン</li> </ul>'
}, {
    'id': 3607,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP3000842',
    'name': '320（インテル）',
    'price': 42595.0,
    'img_url': 'https://www3.lenovo.com/medias/ideapad-320.png?context=bWFzdGVyfC9lbWVhL2ltYWdlcy9wcm9tb3MvbGFwdG9wcy80MDB4MzAwL3wxMDM1NzJ8aW1hZ2UvcG5nfC9lbWVhL2ltYWdlcy9wcm9tb3MvbGFwdG9wcy80MDB4MzAwL2gwMi9oMDkvOTUwMjQzNjc1MzQzOC5wbmd8YWJhMDQwZTZjNjE3N2U0NjRmN2ZhYTE5MDBiODAzZmM5MDUwZWVlOWViOGZmMzZkYjU0MTJkZjEyZmIyMWU4MQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300-series/Ideapad-320-15-Intel/p/88IP3000842',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><ul><li>インテルプロセッサー搭載</li><li>優れたパフォーマンス</li><li>スタイリッシュなデザイン</li></ul>'
}, {
    'id': 3608,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP3000847',
    'name': '320（AMD A,FX）',
    'price': 50890.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-ideapad-320-15-series-front.png?context=bWFzdGVyfHJvb3R8MjY4MTJ8aW1hZ2UvcG5nfGg4Mi9oNTkvOTQzNjQ4NjA0MTYzMC5wbmd8ZTVkOWY5Y2RmZjc5MGQ2NjRjZDgyMDU4ODEwM2NjMzQ0NWYyNjFhMjBhN2U2ZDgxN2UwZGMxZWUzNzViMGVlZg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300-series/Ideapad-320-15-AMD-ABR/p/88IP3000847',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>高性能AMDプロセッサー搭載</li><li>高解像度液晶ディスプレイ搭載</li></ul>'
}, {
    'id': 3609,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP3000850',
    'name': '320（AMD E2,A）',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-ideapad-320-15-series-front.png?context=bWFzdGVyfHJvb3R8MjY4MTJ8aW1hZ2UvcG5nfGg4Mi9oNTkvOTQzNjQ4NjA0MTYzMC5wbmd8ZTVkOWY5Y2RmZjc5MGQ2NjRjZDgyMDU4ODEwM2NjMzQ0NWYyNjFhMjBhN2U2ZDgxN2UwZGMxZWUzNzViMGVlZg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300-series/Lenovo-IdeaPad-320-15AST/p/88IP3000850',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 スタンダードノート</b><br />（量販店モデル）<br /><div>・AMDプロセッサー搭載</div><div>・AMD Radeon搭載</div>'
}, {
    'id': 3610,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP3000719',
    'name': '310（インテル）',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-310-15-back.png?context=bWFzdGVyfGltYWdlc3wxOTM4NHxpbWFnZS9wbmd8aW1hZ2VzL2g4OS9oYTMvOTMyNzkxNzY2MjIzOC5wbmd8YTM3YTAyYWQ2NGMzODk1ODBmMDUzZTZiNGExMDVmZGFjZWJhMWI1Mzc3YTMwNTRhNWI5OWVmZTkzMWIzN2Q3OA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300-series/Ideapad-310-15/p/88IP3000719',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 スタンダードノート</b><br />（量販店モデル）<br /><div>・第6世代インテルプロセッサー</div><div>・Dolby&reg; Advanced Audio&trade; 搭載</div>'
}, {
    'id': 3611,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP70S0929',
    'name': 'Ideapad 720S (13.3型 AMD搭載)',
    'price': 95386.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-720s-13-amd-silver-back.png?context=bWFzdGVyfHJvb3R8MTkzOTd8aW1hZ2UvcG5nfGgxZS9oYzcvOTYyMTQxNjg2OTkxOC5wbmd8YTkyZjZlY2M0MGI1NTZhM2FhZTc3ODUzYjdmNGE3OTM4YTdjNmUwOGI0MGFjMzVkYTBhNDdlZjQ0MWU3NmZlZg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/ideapad-700-series/Ideapad-720S-13-AMD/p/88IP70S0929',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': 'ideapad-700-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型\u3000薄型モバイル</strong><br />【レノボ・ショッピング限定販売】<ul><li>最新AMD Ryzen&trade; プロセッサー搭載</li><li>アルミ仕上げのスタイリッシュデザイン</li><li>Dolby ATMOSテクノロジー、JBL スピーカー搭載</li></ul>'
}, {
    'id': 3612,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP70S0893',
    'name': 'Ideapad 720S（13.3型 インテル搭載）',
    'price': 101309.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-720s-13-silver-400x300.png?context=bWFzdGVyfHJvb3R8NTU0Njh8aW1hZ2UvcG5nfGgwZS9oZmEvOTUzNDMxOTc4ODA2Mi5wbmd8YzcxNWYxMWEzNDk2NDhhYmZlZmEyNzRjYzA2MjIyZjQ4ZDY2MmM2ZGM0NjI4OTZlNDIwOWYwOTAxZjVjODA1NA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/ideapad-700-series/Ideapad-720S-13-Intel/p/88IP70S0893',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': 'ideapad-700-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型 薄型モバイル</strong><br />【レノボ・ショッピング限定販売】<ul><li>インテル&reg; Core&trade; プロセッサー搭載</li><li>アルミ仕上げのスタイリッシュデザイン</li><li>Dolby ATMOSテクノロジー、JBL スピーカー搭載</li></ul>'
}, {
    'id': 3613,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP70S0895',
    'name': 'Ideapad 720S（15.6型）',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-720s-15-nav-thumb.png?context=bWFzdGVyfHJvb3R8MTA1NTN8aW1hZ2UvcG5nfGg5Mi9oODUvOTU4NjY0MDYxNzUwMi5wbmd8OTA1NDJmMGZkZmNmYjQzMjJlNWVmZWE2ODEwNGM4Y2NmZDRkNmRiMTgwNjE2NTg4NzM1ZDRhMzI5ZjA1YTRiYg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/ideapad-700-series/Ideapad-720S-15/p/88IP70S0895',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': 'ideapad-700-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型\u3000薄型ノート</strong><p>【量販店モデル】</p> <ul><li>インテル&reg; Core&trade; プロセッサー搭載</li> <li>アルミ仕上げのスタイリッシュデザイン</li> <li>Dolby ATMOSテクノロジー、JBL スピーカー搭載 </li></ul>'
}, {
    'id': 3614,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88GMY500808',
    'name': ' Legion Y520 ',
    'price': 101477.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-legion-y520-15-front.png?context=bWFzdGVyfGltYWdlc3wyNzI1M3xpbWFnZS9wbmd8aW1hZ2VzL2hiMS9oMDQvOTQxMjY3NTUwMjExMC5wbmd8YjYxMzUxYzUwZDcyNmEyYjJmN2Y1MmQyZTAxYmI4NmY5Yjg4N2Y0ZjIxMWI0YzYyMTM3YTBiZmMyYjZjZGY4Ng',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/legion-y-series/Legion-Y520/p/88GMY500808',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': 'legion-y-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ゲーミングノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>ゲームをカジュアルに楽しめる</li><li>効果的な放熱対策で快適に</li></ul>'
}, {
    'id': 3615,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88GMY700794',
    'name': 'Legion Y720',
    'price': 135864.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-legion-y720-15-front.png?context=bWFzdGVyfGltYWdlc3wyNTQ5NXxpbWFnZS9wbmd8aW1hZ2VzL2hkMS9oN2MvOTQxMjY3NjU1MDY4Ni5wbmd8YThiZGUyZTEwN2MxMDc3YTc2NWM4NTY1MmJkMmI1OWQ5NjJjY2NlYmZlZmEyNzEwZGJjMDFhNTI2Y2E2ZDA5Mg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/legion-y-series/Legion-Y720/p/88GMY700794',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': 'legion-y-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ゲーミングノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>高性能グラフィック搭載</li><li>超高速データ転送ストレージ</li></ul>'
}, {
    'id': 3616,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXX16G',
    'name': 'ThinkPad X1 Carbon (2018モデル)',
    'price': 162043.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-Thinkpad-X1-Carbon-series.png?context=bWFzdGVyfC9lbWVhL2ltYWdlcy98MTEwMTI4fGltYWdlL3BuZ3wvZW1lYS9pbWFnZXMvaDU3L2gzNS85NjY0NDI2NjcyMTU4LnBuZ3w4MzFmNmI5MWQ2ODkxOTJkMDNlZmY3MzlmMGU1MjA4MWFiMzBhMThiNDNiOGZlN2I3ZTJkMzBmMGQwMzdiYTE4',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X1-Carbon-6th-Gen/p/22TP2TXX16G',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 薄型軽量モバイル</strong> <ul><li>第8世代インテル&reg; Core&trade;プロセッサー選択可能</li><li>洗練されたスタイリッシュなデザイン</li><li>HDR WQHD IPS液晶を選択可能</li></ul>'
}, {
    'id': 3617,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXX13Y',
    'name': 'ThinkPad X1 Yoga(2018モデル)',
    'price': 174096.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-thinkpad-x1-yoga-series.png?context=bWFzdGVyfHJvb3R8MTg4NDV8aW1hZ2UvcG5nfGhhNi9oYTEvOTYwNDEzOTEyMjcxOC5wbmd8NmIzYmI2M2I2ZjZjZDQ5YjlhMDEwOWUwNTY3YmJmZTZiMTk2NDc4ZmQ4NTQwZjM1M2JjODQyZGMyNGViN2UxMA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X1-Yoga-3rd-Gen/p/22TP2TXX13Y',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 マルチモード</strong> <ul><li>第8世代インテル&reg; Core&trade;プロセッサー選択可能</li><li>利用シーンに合わせて4つのモードで使える</li><li>HDR WQHD IPS液晶を選択可能</li></ul>'
}, {
    'id': 3618,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TX2800',
    'name': 'ThinkPad X280',
    'price': 98453.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-x280-front.png?context=bWFzdGVyfC9lbWVhL2ltYWdlcy98MTYxMjR8aW1hZ2UvcG5nfC9lbWVhL2ltYWdlcy9oNzQvaGE3Lzk2NjMwMjIxMzczNzQucG5nfDllMGM5N2U3ZGZmOGQ0ODYzNDkyZWZiOTVlMzY5NGQzZWIzZWQ1YjVjY2Q0Zjk2OWQxN2JhYmM0MWQ1ZTYxYzM',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X280/p/22TP2TX2800',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>12.5型 ビジネスモバイル</strong><br /><ul><li>より軽量でスリムに進化</li><li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li><li>約1.13kgの軽量化を実現</li></ul>'
}, {
    'id': 3619,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXX380',
    'name': 'ThinkPad X380 Yoga',
    'price': 150660.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-x380-2-in-1-front.png?context=bWFzdGVyfHJvb3R8MTg5Njd8aW1hZ2UvcG5nfGgwMC9oNDcvOTYxNzc5NDAzOTgzOC5wbmd8OGRkNWU5YjE2NDI0MjgyOTVhM2JhNmIzOTIzNmVmZjU5NWQxNGQ5ZjRkNmJhMjUxN2ViYzFkNDE4MjZkMGZjMQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X380-Yoga/p/22TP2TXX380',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型マルチモードPC</strong><br /><ul><li>さまざまなスタイルで使える</li><li>生産性を高める豊富な機能</li><li>強化されたセキュリティ</li></ul>'
}, {
    'id': 3620,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXX15G',
    'name': 'ThinkPad X1 Carbon（2017モデル）',
    'price': 142560.0,
    'img_url': 'https://www3.lenovo.com/medias/x1-carbon-gen5-white-yonezawa-400x300.png?context=bWFzdGVyfHJvb3R8Njg3MjV8aW1hZ2UvcG5nfGgzZS9oMDUvOTQ2Njg4ODU4NTI0Ni5wbmd8OWFmNDc0YjAzMzc2NmUxMTM1MDE2YjUzMDNjYTU1MzYyMzMzMmUwZjRjZDA4ZmEwYmZmZTRiMDQ0NmQyMzMyNQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X1-Carbon-5th-Gen/p/22TP2TXX15G',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 薄型軽量モバイル</strong><ul><li>ハイパフォーマンスモバイル</li><li>重さわずか1.13 kg～</li><li>厳格な品質テスト、高い信頼性</li></ul>'
}, {
    'id': 3621,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXX12Y',
    'name': 'ThinkPad X1 Yoga（2017モデル）',
    'price': 146966.0,
    'img_url': 'https://www3.lenovo.com/medias/thinkpad-x1-yoga-gen2-400x300-yonezawa.png?context=bWFzdGVyfHJvb3R8Njc5Mzh8aW1hZ2UvcG5nfGgyNi9oZmEvOTU0OTAyMzM0NjcxOC5wbmd8YTk4ZjkyYTZmN2RhMjRiMGQ2OWFlMjNmYjllZTQ4NzA0YWQ0NDk5ZWMxZmQ4MjBhZWY1OGJjNjNkM2FhNTdjYw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/Thinkpad-X1-Yoga-2nd-Gen/p/22TP2TXX12Y',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 マルチモード</strong><br /><ul><li>軽量 2 in 1モバイルノート</li><li>柔軟に変えられる4つの使い方</li><li>タッチパネルで直感的な操作</li></ul>'
}, {
    'id': 3622,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TX2700',
    'name': 'ThinkPad X270',
    'price': 99727.0,
    'img_url': 'https://www3.lenovo.com/medias/thinkpad-x270-yonezawa-400x300.png?context=bWFzdGVyfHJvb3R8ODExMTB8aW1hZ2UvcG5nfGg5MC9oNWEvOTQ3NzY4NzgzNjcwMi5wbmd8M2ZjZjdmZDMxN2VmYTA3ZjkzOTBlMmUzNGI3OWY3MjQ5ZjhiNWYzMTI2YWRhZmMyOWFjM2VlYTZjY2Q4MDQ5Yg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/x-series/ThinkPad-X270/p/22TP2TX2700',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'x-series',
    'date': '2018-05-27',
    'description': '<strong>12.5型 ビジネスモバイル</strong><br /><ul><li>あらゆるビジネスシーンに最適</li><li>高いパフォーマンスと携帯性</li><li>厳格な品質テスト、高い信頼性</li></ul>'
}, {
    'id': 3623,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88YG7000919',
    'name': 'Yoga 720',
    'price': 74174.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-yoga-y720-front.png?context=bWFzdGVyfHJvb3R8MTEyOTg5fGltYWdlL3BuZ3xoNjgvaDdlLzk1MDYwNjQyNjkzNDIucG5nfDA3ZmMxNDliZTRlZjY0YjJlYjNhNGExMGY3ZDRhMGI3ZGMwZjlmODQ3MzQ1NmQxNDg1MTEwN2Q4NTIzNjA4Zjc',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-700-series/Yoga-720-12/p/88YG7000919',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-700-series',
    'date': '2018-05-27',
    'description': '<strong>12.5型マルチモードモバイル</strong><ul><li>第7世代インテルプCore&trade;ロセッサー</li><li>モードを切り替えてスタイル自由</li><li>薄型、軽量で持ち運びやすい</li></ul>'
}, {
    'id': 3624,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPP52S',
    'name': 'ThinkPad P52s',
    'price': 158468.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p52s-front.png?context=bWFzdGVyfHJvb3R8MjEwMzJ8aW1hZ2UvcG5nfGg1Ni9oZDUvOTU5MjI1NzU0NDIyMi5wbmd8NTI4MDg0Y2NkNDZjNGEyNTMwOTQyZWVhYTg5MzkwZWE1ZWU0NjBiMjM1ZDNjNmViMjllODQ5OGU3NjdmMGQ4NQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P52s/p/22TP2WPP52S',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'p-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ワークステーション</strong><ul><li>高速なプロセッサーとグラフィックス搭載</li><li>優れたパフォーマンスとモビリティ</li></ul>'
}, {
    'id': 3625,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPWP51',
    'name': 'ThinkPad P51',
    'price': 191873.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p51-front.png?context=bWFzdGVyfHJvb3R8MTkwNzZ8aW1hZ2UvcG5nfGg2Yy9oNmYvOTQzNjU5NDI3NDMzNC5wbmd8M2VjNzM1NDk4NDQwMzNjMGU3NmQ1OTkyMGQyMzViNDM0YWMxYjVlZGNjNDc2NDM2YTQxOGJmNjhiMTk3NmE5Mg',
    'url': 'https://www3.lenovo.com/jp/ja/workstations/thinkpad-p-series/P51/p/22TP2WPWP51',
    'spliter': 'workstations',
    'brand': 'undefined',
    'series': 'thinkpad-p-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ワークステーション</strong><ul><li>モバイルXeon搭載可能</li><li>高性能グラフィックカード対応</li></ul>'
}, {
    'id': 3626,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPP51S',
    'name': 'ThinkPad P51s',
    'price': 145325.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p51s-front.png?context=bWFzdGVyfGltYWdlc3wxNDc1OHxpbWFnZS9wbmd8aW1hZ2VzL2hiNy9oNzQvOTQyMzgyNDk0NTE4Mi5wbmd8YjJkYmNkZjM1ZTBiNmYzMmM5NDFkNzBiMjQ3MDBhZDcwMTMzOGRhZmI4ZGI4ODcwZjBhMGNjYmZhNTY3NTZjMw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/Thinkpad-P51s/p/22TP2WPP51S',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'p-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ワークステーション</strong><ul><li>第7世代インテルプロセッサー</li><li>第7世代インテルプロセッサー</li></ul>'
}, {
    'id': 3627,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPWP71',
    'name': 'ThinkPad P71',
    'price': 215460.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p71-front.png?context=bWFzdGVyfGltYWdlc3wxOTMwOXxpbWFnZS9wbmd8aW1hZ2VzL2gzNi9oNGMvOTQwMjAxMDM3MDA3OC5wbmd8OGE0MzhiNjZiMmVmMzE0OGNiNWIyY2ExNTM1ZTY5ODI5MWZjNjY1ZjM4N2E4YzVkZTdiMWMxMjIyMWQ4OWQ0Mw',
    'url': 'https://www3.lenovo.com/jp/ja/workstations/thinkpad-p-series/ThinkPad-P71/p/22TP2WPWP71',
    'spliter': 'workstations',
    'brand': 'undefined',
    'series': 'thinkpad-p-series',
    'date': '2018-05-27',
    'description': '<strong>17.3型 ワークステーション</strong><ul><li>モバイルXeon搭載可能</li><li>VR対応ワークステーション</li></ul>'
}, {
    'id': 3628,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPWP50',
    'name': 'ThinkPad P50',
    'price': 158285.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p50s-front.png?context=bWFzdGVyfGltYWdlc3w2NTgzMnxpbWFnZS9wbmd8aW1hZ2VzL2g1OC9oMDYvOTM0NDY3NzM0NzM1OC5wbmd8ZTBhMDQxOGEzOTNmYWVlNzU5Y2NiNmViM2FiODY2OWRhOTViNmZlN2IxMGVhY2FkNzQ5NzJjNGM1ZWIzNDJhMQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P50/p/22TP2WPWP50',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'p-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ワークステーション</strong><ul><li>モバイルXeon搭載可能</li><li>高性能グラフィックカード対応</li></ul>'
}, {
    'id': 3629,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2WPWP70',
    'name': 'ThinkPad P70',
    'price': 202608.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-p70-front.png?context=bWFzdGVyfGltYWdlc3w1ODQwMnxpbWFnZS9wbmd8aW1hZ2VzL2g4MC9oOTgvOTM0NDY4MDI5NjQ3OC5wbmd8ZDNlOTUzYWFlYTdhZmYwNjVhMWQzMGE3NWI4ZDNhZmU5ZDJjNzAxMzFmYjE3N2U5NGE1MDNhN2QzZTE2OGIzOA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/p-series/ThinkPad-P70/p/22TP2WPWP70',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'p-series',
    'date': '2018-05-27',
    'description': '<strong>17.3型 ワークステーション</strong><ul><li>モバイルXeon搭載可能</li><li>高性能グラフィックカード対応</li></ul>'
}, {
    'id': 3630,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88LG80V0853',
    'name': 'V720',
    'price': 88560.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-720-14in-series-front.png?context=bWFzdGVyfHJvb3R8MjgyNTd8aW1hZ2UvcG5nfGg3NS9oNWEvOTU4NDM5MTM4OTIxNC5wbmd8YzlhMTg1YWQyNjQzNTdiOWM4NjViMzNiY2FmNDEyZTNiY2UxZmQxMDM4NTYzOTAwZTQ5YzU5M2NiMzNhNTU5MQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/v-series/Lenovo-V720-14/p/88LG80V0853',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'v-series',
    'date': '2018-05-27',
    'description': '<ul><strong>14.0型\u3000ビジネスノート</strong><li>第7世代インテル® Core™ プロセッサー</li><li>スタイリッシュなデザイン</li><li>優れたセキュリティ</li></ul>'
}, {
    'id': 3631,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88LG80V0697',
    'name': 'V310（14）',
    'price': 38630.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-v310-14-back.png?context=bWFzdGVyfGltYWdlc3wxMzY0NnxpbWFnZS9wbmd8aW1hZ2VzL2gyNC9oOGYvOTMyNzkyNzM2MTU2Ni5wbmd8MDEyMDNhZGM3OWEwZTA5ODJjMzNiZjEzN2MzNGE4YTdjZTU2NmY5ZWRhNjQ2ZGRmYzQ0MjZjYTQwOTM5ZDQyNw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/v-series/V310-14/p/88LG80V0697',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'v-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 スタンダードノート</strong><br /><ul><li>第6世代インテルプロセッサー</li><li>高いコストパフォーマンス</li></ul>'
}, {
    'id': 3632,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88LG80V0698',
    'name': 'V310（15）',
    'price': 39960.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-v310-15-back.png?context=bWFzdGVyfGltYWdlc3wxOTk3NnxpbWFnZS9wbmd8aW1hZ2VzL2hhMy9oYzMvOTMyNzkyOTQ5MTQ4Ni5wbmd8Yjg4OWRiZGNiOTUzOGQ3MmIwZTNmODY0MjFmM2MyM2Y5ZTBjNWI2MGZmYjFjYzJkYmYwMWI2YmRlNzY3N2ZhOQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/v-series/V310-15/p/88LG80V0698',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'v-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>第6世代インテルプロセッサー</li><li>高いコストパフォーマンス</li></ul>'
}, {
    'id': 3633,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88LG80V0702',
    'name': 'V310（15 第7世代インテル）',
    'price': 64800.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-v310-15-back.png?context=bWFzdGVyfGltYWdlc3wxOTk3NnxpbWFnZS9wbmd8aW1hZ2VzL2hjZS9oNGYvOTM0OTc5MTE4Njk3NC5wbmd8YjA5YmJiYjUyZDgwODMwMjRjY2IyYjRkZjkyMTg4MjA3NTg4NmYyYzlhYzA4ODkwMDJiODQzOTVhNzQzMzhmYw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/v-series/Lenovo-V310-15IKB/p/88LG80V0702',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'v-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>第7世代インテルプロセッサー</li><li>高いコストパフォーマンス</li></ul>'
}, {
    'id': 3634,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP10S0892',
    'name': 'Ideapad 120S（14型）',
    'price': 45727.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-120s-14-back.png?context=bWFzdGVyfHJvb3R8MjI1NzF8aW1hZ2UvcG5nfGhiZS9oMmIvOTQ5NDA1ODUzMjg5NC5wbmd8NmEwMTgzZDY4NjgwNTExNTc3ZWVlYmU3MGM1YTkxN2FmNmQ1MzAwNTAwNGJiNzI0ZGJlMzc4ZmUwMzA1OTg2ZQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/100s-series/Ideapad-120S-14-Intel/p/88IP10S0892',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '100s-series',
    'date': '2018-05-27',
    'description': '<strong>14型 スタイリッシュなノートパソコン</strong><br />【レノボ・ショッピング限定販売】<ul><li>シンプルでスタイリッシュ</li><li>鮮やかな映像のディスプレイ</li><li>優れれたコストパフォーマンス</li></ul>'
}, {
    'id': 3635,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP10S0891',
    'name': 'Ideapad 120S（11型）',
    'price': 40640.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-120s-11-back.png?context=bWFzdGVyfHJvb3R8MjA5MTd8aW1hZ2UvcG5nfGgxYi9oZmIvOTQ5NDA1OTc3ODA3OC5wbmd8ZTM4OWQ5NGNmOTNmODMyMjY0ZmE4ZTM0YzkwOTU0ZThmN2QzYWM0ZTQyNGM5NjYyYWEzZTM4NjNhMzUxNTVjZg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/100s-series/Ideapad-120S-11-Intel/p/88IP10S0891',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '100s-series',
    'date': '2018-05-27',
    'description': '<strong>11.6型 エントリーモバイル</strong><ul><li>コンパクトでスタイリッシュ</li><li>優れたコストパフォーマンス</li></ul>'
}, {
    'id': 3636,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP10S0803',
    'name': 'Ideapad 110S',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-110s-11-back.png?context=bWFzdGVyfGltYWdlc3wxMTczNXxpbWFnZS9wbmd8aW1hZ2VzL2hhYi9oN2UvOTM5MDk2MzU1NjM4Mi5wbmd8MmQ3MmM1YjhmMGJhNWYyY2U3MzBhNWZjMDFhODBlZjY0YzE1MTNkMzg4NjE0MzhmNjkzZDRhNjZmNzM2MjViNw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/100s-series/Ideapad-110S-11-Intel/p/88IP10S0803',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '100s-series',
    'date': '2018-05-27',
    'description': '<b>11.6型 エントリーモバイル</b><br />（量販店モデル）<br /><div><div>・コンパクトで優れた携帯性</div><div>・優れたコストパフォーマンス</div></div>'
}, {
    'id': 3637,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TXY370',
    'name': 'ThinkPad Yoga 370',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/thinkpad-yoga-370-400x300.png?context=bWFzdGVyfGltYWdlc3w4MTU1MHxpbWFnZS9wbmd8aW1hZ2VzL2hjNi9oOWYvOTQwMzk0NDY2NTExOC5wbmd8MDEyYmUyMWNlMWM3MjBiZTAwZGJiM2MzMTdmNGM0N2EwMGYxNjcyNWFlMTZjZWUwNGFiZTY2Y2ZkN2YxNjJhMw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/yoga-series/Yoga-370/p/22TP2TXY370',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'yoga-series',
    'date': '2018-05-27',
    'description': '<strong>13.3型 マルチモード</strong><br /><ul><li>用途に合わせた自由なスタイル</li><li>タッチパネルで快適な操作性</li></ul>'
}, {
    'id': 3638,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP5000868',
    'name': 'Ideapad 520 ',
    'price': 70200.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-ideapad-520-15-series-front.png?context=bWFzdGVyfHJvb3R8MTA0NDA0fGltYWdlL3BuZ3xoMDIvaGUzLzk0NDA2MDQyOTExMDIucG5nfGUwYzcxYTRkMzc2MWQ5M2QyNDhkNmU4YzYyZDQyY2NjN2FiN2I2MmY4Y2Q1YTE3MjgzODdkNTA3MjkzNzJmMWE',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/500-series/Ideapad-520-15-Intel/p/88IP5000868',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '500-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 マルチメディアノート</strong><br />【レノボ・ショッピング限定販売】<ul><li>高解像度液晶ディスプレイ搭載</li><li>優れたパフォーマンス</li><li>高品質なサウンドを実現</li></ul>'
}, {
    'id': 3639,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TEE480',
    'name': 'E480',
    'price': 54605.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-e480-14-series-front.png?context=bWFzdGVyfHJvb3R8Njg3ODF8aW1hZ2UvcG5nfGhiMy9oM2UvOTY1NzQyNjI0NzcxMC5wbmd8OTBmMzNlZDA1YjFkN2ViZGI3MDMzOTE3OTM0NWQxZDA5ODJhNjRjYWMwNmMzZTY4NmUyMjY0ZjUwNWE0Y2E0Yg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/e-series/ThinkPad-E480/p/22TP2TEE480',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'e-series',
    'date': '2018-05-27',
    'description': '<b>14.0型 スタンダードノート</b><br /><ul><li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li><li>ビジネスの生産性を高めるノート</li></ul>'
}, {
    'id': 3640,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TEE580',
    'name': 'E580',
    'price': 54886.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-e580-front.png?context=bWFzdGVyfHJvb3R8NzkyMDR8aW1hZ2UvcG5nfGgyMy9oZWIvOTY1NzQyNjMxMzI0Ni5wbmd8NGRiNjNjMWZmYjdlYzk2MjI3MGE3ODNhZDU5MWM5ZTc4ZjVjYjA0OTNmYmZmOTk5ZGNjMTlmZDlmZWExZGNjNA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/e-series/ThinkPad-E580/p/22TP2TEE580',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'e-series',
    'date': '2018-05-27',
    'description': '<b>15.6型 スタンダードノート</b><br /><ul><li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li><li>ビジネスの生産性を高めるノート</li></ul>'
}, {
    'id': 3641,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TEE470',
    'name': 'E470',
    'price': 50544.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-e470-front.png?context=bWFzdGVyfGltYWdlc3w3MjE2OXxpbWFnZS9wbmd8aW1hZ2VzL2g2ZC9oZjAvOTM0OTc3NzQ1NzE4Mi5wbmd8NWZiZDRlYzY4Zjc0YjRjYjIzZjNmZDg0Y2MzNzgwNmE3MjQ0OTM4MzdkN2FlMzY3ODA4YzRjNzE2MjRjM2RjNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/e-series/ThinkPad-E470/p/22TP2TEE470',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'e-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 スタンダードノート</strong><br /><ul><li>第7世代インテルプロセッサー</li><li>セキュリティーに優れたノート</li></ul>'
}, {
    'id': 3642,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TEE570',
    'name': 'E570',
    'price': 82620.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-e570-front.png?context=bWFzdGVyfGltYWdlc3w3MTkxMHxpbWFnZS9wbmd8aW1hZ2VzL2gwMy9oYTcvOTM0OTc4MDU3MDE0Mi5wbmd8NmRmMjZhNTNjNTVjOTRhYjBmY2VhYjk4M2VkNjM3YmZhNGUyNWQ3Yzk4YmIyNmEyZTBjZjBhNDUwMTI3YzliZQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/e-series/Thinkpad-E570/p/22TP2TEE570',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'e-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><br /><ul><li>第7世代インテルプロセッサー</li><li>セキュリティーに優れたノート</li></ul>'
}, {
    'id': 3643,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TEE575',
    'name': 'E575',
    'price': 50976.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-e575-front.png?context=bWFzdGVyfGltYWdlc3w3MTkwNXxpbWFnZS9wbmd8aW1hZ2VzL2g4Ni9oODAvOTM0OTc4MzA5MzI3OC5wbmd8NTMwZWU4YmU0MGQzNzAxNjllOTZlOThmZjVjOTRkYjk1MThhMDQ4MTZiYTUxYWUwOTRmMTU0N2I1ODM0NmMzNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/e-series/ThinkPad-E575/p/22TP2TEE575',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'e-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 スタンダードノート</strong><br /><ul><li>AMDプラットフォーム搭載</li><li>ビジネスシーンを快適にする</li></ul>'
}, {
    'id': 3644,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88ELC1S9998',
    'name': '500e Chromebook',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-chromebook-500e-front.png?context=bWFzdGVyfHJvb3R8MjYyMzZ8aW1hZ2UvcG5nfGg1OC9oNjQvOTYyNDk0MzA2NzE2Ni5wbmd8OGRiM2VlN2Q2ZDlkZDYyMTc3NDEzMTYxOGU5MThlNWE1ZTNhZDJlMjRkYTI2MWVlNzYwNmFjMzVlNTk1YWJjZQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/lenovo-n-series/500e-Chromebook/p/88ELC1S9998',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'lenovo-n-series',
    'date': '2018-05-27',
    'description': '<b>11.6型</b><br /><ul> <li>Chrome OS搭載 2 in 1</li> <li>Lenovo 電子ペン添付</li> <li>堅牢性に優れたボディ</li> </ul>'
}, {
    'id': 3645,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88ELC1S9997',
    'name': '300e Chromebook',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-chromebook-300e-front.png?context=bWFzdGVyfHJvb3R8MjgyNzF8aW1hZ2UvcG5nfGg0NS9oMzMvOTYyMzc3MDU5NTM1OC5wbmd8ZDU4OWZlNjQ1ZDEwMTFjMDMwNDc3ZTk0ZGE3YTgyMjUwZmVmMGYxY2I1OTY0ZDFlZWVkNjg1ZjE3NTk2YmQzNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/lenovo-n-series/300e-Chromebook/p/88ELC1S9997',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'lenovo-n-series',
    'date': '2018-05-27',
    'description': '<b>11.6型</b><br /><ul> <li>Chrome OS搭載 2 in 1</li> <li>10点マルチタッチ対応</li> <li>堅牢性に優れたボディ</li> </ul>'
}, {
    'id': 3646,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88EL10S1024',
    'name': 'Lenovo 300e',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-300e-windows-front.png?context=bWFzdGVyfHJvb3R8MjAyNjV8aW1hZ2UvcG5nfGg1ZS9oZjUvOTYyMjE5MDQyNDA5NC5wbmd8YmNlOWM0MjllYTU0NGU5NTcyZjZlYmRjNDkxOWM2MjQ3NTViNTgwOTdkYTBhM2RmNmQyMDc3NTMyMGY3NWY1ZQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/lenovo-n-series/300e/p/88EL10S1024',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'lenovo-n-series',
    'date': '2018-05-27',
    'description': '<b>11.6型</b><br /><div>・モードを切り替え可能</div><div>・堅牢性に優れた筐体</div><div>・長時間バッテリ駆動</div>'
}, {
    'id': 3647,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88EL10S0898',
    'name': 'Lenovo N24',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-N24-front.png?context=bWFzdGVyfHJvb3R8OTM2OTl8aW1hZ2UvcG5nfGgwZS9oY2EvOTQ1NDMwNjI2MzA3MC5wbmd8YmVjZmJmM2M1NWQ2ZjI5ZjQ3MmVmNGM0MzY1Nzg5YmZjMzcxNTM1YWE3YjNlZjgxMDdkNWFkZDViYjE0YWJiYQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/lenovo/lenovo-n-series/N24/p/88EL10S0898',
    'spliter': 'notebooks',
    'brand': 'lenovo',
    'series': 'lenovo-n-series',
    'date': '2018-05-27',
    'description': '<b>11.6型</b><br /><div>・4つのモードで利用可能</div><div>・堅牢性に優れた設計</div><div>・ペン入力にも対応</div>'
}, {
    'id': 3648,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TT480S',
    'name': 'T480s',
    'price': 136080.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-t480s-front.png?context=bWFzdGVyfHJvb3R8MjQxNDB8aW1hZ2UvcG5nfGhjOC9oMjUvOTYxMTE4NDYwMzE2Ni5wbmd8YmUwMDlhN2RmMjk3NWYxZjY5NjFkZmU2YzA5ZjI1NDE3NTE3Nzc1ZTJiYzM3OGRhZDBhZDhjOTcyZTU4NjcwOA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/t-series/ThinkPad-T480s/p/22TP2TT480S',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 't-series',
    'date': '2018-05-27',
    'description': '<b>14.0型 ハイスペックモバイル</b><br /> <ul> <li>軽量、薄型のデザイン</li> <li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li> <li>高性能グラフィック NVIDIA Geforce 選択可能</li> </ul>'
}, {
    'id': 3649,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TT4800',
    'name': 'T480',
    'price': 108086.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-t480-front.png?context=bWFzdGVyfHJvb3R8MjE4MDJ8aW1hZ2UvcG5nfGhlMS9oYjgvOTYxMDcwOTQ2NzE2Ni5wbmd8ZDFhMTU2NjU3MjY5ZDMzYWFmODQ4NzM0ZDIwMGQ0YTVjYTgzNmU1OWQ1NDQxZGM3NzRhNzBiMGFiMjZhM2M1OA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/t-series/ThinkPad-T480/p/22TP2TT4800',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 't-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 ハイパフォーマンス</strong><ul><li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li><li>強化されたセキュリティ</li><li>厳格な品質テスト、高い信頼性</li></ul>'
}, {
    'id': 3650,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TT5800',
    'name': 'T580',
    'price': 121306.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-t580-front.png?context=bWFzdGVyfHJvb3R8MjQ2OTR8aW1hZ2UvcG5nfGhkNS9oZDYvOTYxMTE4OTcxNDk3NC5wbmd8ZWYzZDRmY2Q0MzI0M2NkYTI0ZTllYjM2ZmI4ZjFmZWRiMTMwYzQ3ZjNjNzk3NzZhNDhiN2I3MTQ5NzRjYjNmYg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/t-series/ThinkPad-T580/p/22TP2TT5800',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 't-series',
    'date': '2018-05-27',
    'description': '<strong>15.6型 ハイパフォーマンス</strong><ul><li>高解像度のUltra HD IPS液晶を選択可能</li><li>第8世代インテル&reg; Core&trade; プロセッサー搭載可能</li><li>強化されたセキュリティ</li></ul>'
}, {
    'id': 3651,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TT470S',
    'name': 'T470s',
    'price': 134503.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-t470s-400x300.png?context=bWFzdGVyfGltYWdlc3w3MjY1NnxpbWFnZS9wbmd8aW1hZ2VzL2hmNC9oNjUvOTQwMzk0NDM3MDIwNi5wbmd8NGY5NDE4Y2E0MDg5MzljYmRjYjljNjVkM2VjNTdiYWUxMDNiYzJmNmZhNWNlMWRkYjZmOGU1Nzk5ZTc5YTk5ZA',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/t-series/ThinkPad-T470s/p/22TP2TT470S',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 't-series',
    'date': '2018-05-27',
    'description': '<strong>14.0型 ハイパフォーマンス</strong><br /><ul><li>モバイルからデスクワークまで</li><li>あらゆるビジネスシーンに最適</li><li>厳格な品質テスト、高い信頼性</li></ul>'
}, {
    'id': 3652,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TAA475',
    'name': 'A475',
    'price': 73224.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-a475-front.png?context=bWFzdGVyfHJvb3R8MTk5NDV8aW1hZ2UvcG5nfGhkZS9oNjcvOTUyMDIxMzUyNDUxMC5wbmd8YzBlZWRjZjE0ZjFhYWZiNmVkMzM4NjMwYmVjNzgyOWE1NTk1ZjM2OGViMjQ3Y2U1MTZmNzIyMTJkOWQ2YzNkNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/thinkpad-a-series/ThinkPad-A475/p/22TP2TAA475',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'thinkpad-a-series',
    'date': '2018-05-27',
    'description': '<strong>1４.0型 ビジネスノート</strong><br /><ul><li>最新のAMDプロセッサー搭載</li><li>パワフルなパフォーマンス</li><li>高度なセキュリティと高い信頼性</li></ul>'
}, {
    'id': 3653,
    'site': 'jp',
    'language': 'ja',
    'article_number': '22TP2TA2750',
    'name': 'A275',
    'price': 64519.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-thinkpad-a275-front.png?context=bWFzdGVyfHJvb3R8Njc5MDR8aW1hZ2UvcG5nfGgwNS9oMzQvOTU3NzYzNTQ3OTU4Mi5wbmd8Zjg2MzA2OTRlOGMyNjY1ZjAxMTRlNTRkYTU2OWFlMTFjMWFhNzU1NDJkYWVmZmMxNGU4MjQ3NTMwNWJhMTRmYw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/thinkpad/thinkpad-a-series/ThinkPad-A275/p/22TP2TA2750',
    'spliter': 'notebooks',
    'brand': 'thinkpad',
    'series': 'thinkpad-a-series',
    'date': '2018-05-27',
    'description': '<strong>12.5型 ビジネスモバイル</strong><br /><ul><li>最新のAMDプロセッサー搭載</li><li>高いパフォーマンスと携帯性</li><li>高度なセキュリティと高い信頼性</li></ul>'
}, {
    'id': 3654,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP30S0987',
    'name': '330S (14)',
    'price': 56436.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-330s-14-front-platinum.png?context=bWFzdGVyfHJvb3R8MTM2NzA3fGltYWdlL3BuZ3xoMDAvaGY0Lzk3Mzg1Mjk1MDUzMTAucG5nfDI2N2YwYzEzMWJhMGIxYTZjOWJkZTY2NGVlMTk1ZTFjMTc4ZGY4MmM3YjAzMzFhZmY3ZDI1OWY3ODE2MTUxZjQ',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300s-series/Ideapad-330S-14-Intel/p/88IP30S0987',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300s-series',
    'date': '2018-05-27',
    'description': '14型スリムノート<br />【レノボ・ショッピング限定販売】 <ul> <li>薄くて軽い、ナローベゼル</li> <li>鮮明な FHD IPS液晶</li> <li>豊富なCPUをラインアップ</li> </ul>'
}, {
    'id': 3655,
    'site': 'jp',
    'language': 'ja',
    'article_number': '88IP30S0902',
    'name': 'Ideapad 320S(13)',
    'price': 'null',
    'img_url': 'https://www3.lenovo.com/medias/lenovo-laptop-ideapad-320s-13in-series-front.png?context=bWFzdGVyfHJvb3R8MzAwMTB8aW1hZ2UvcG5nfGhiZi9oZDAvOTUzNTI3NzIzNjI1NC5wbmd8YTgzNGJiZDcyOTgxNTNmYjk4ODRiNWFhMmY3ZWYxY2Y5ZDNlMjllNzMxOTUyMmFkY2VkZjZhZTIyNjNjZmIwNw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/ideapad/300s-series/Ideapad-320S-13/p/88IP30S0902',
    'spliter': 'notebooks',
    'brand': 'ideapad',
    'series': '300s-series',
    'date': '2018-05-27',
    'description': '<ul>13.3型エントリーノート<li>スリムでコンパクト</li><li>スタイリッシュなデザイン</li><li>パワフルなプロセッサー</li></ul>'
}, {
    'id': 3656,
    'site': 'jp',
    'language': 'ja',
    'article_number': 'ZZITZTOYB1F',
    'name': 'Yoga Book',
    'price': 45429.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-yoga-book-android-front.png?context=bWFzdGVyfGltYWdlc3w3MzMyMXxpbWFnZS9wbmd8aW1hZ2VzL2hiOC9oYWIvOTMzOTk1ODYyNDI4Ni5wbmd8N2MxNTMxYzg2NmUxMTRlMDliMTRhNDkzY2ZhYzQ3NjQzYjgyNzUzN2JhYjM1MTUxMTBmMTQyNWVlZjY1MmQxNg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-book/Lenovo-Yoga-Book/p/ZZITZTOYB1F',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-book',
    'date': '2018-05-27',
    'description': '<strong>10.1型 2in1タブレット</strong><br />（Wi-Fiモデル）<ul><li>BOOK UI(Android)</li><li>長時間バッテリー駆動</li></ul>'
}, {
    'id': 3657,
    'site': 'jp',
    'language': 'ja',
    'article_number': 'ZZITZTOYB1L',
    'name': 'Yoga Book',
    'price': 50181.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-yoga-book-android-front.png?context=bWFzdGVyfGltYWdlc3w3MzMyMXxpbWFnZS9wbmd8aW1hZ2VzL2gxYi9oZTgvOTM2ODc3Nzk0OTIxNC5wbmd8MjI3NjUzYzJlNDRlMzg3ZTk0NTFjNmFlMTMzMzNmZTkyYjNmOWE4ZDc5ZmZiZDMzZTlkNjExYTYwZmJmZGVjMg',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-book/Lenovo-YB1-X90L/p/ZZITZTOYB1L',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-book',
    'date': '2018-05-27',
    'description': '<strong>10.1型 2in1タブレット</strong><br />（LTE対応モデル）<ul><li>BOOK UI(Android)</li><li>長時間バッテリー駆動</li></ul>'
}, {
    'id': 3658,
    'site': 'jp',
    'language': 'ja',
    'article_number': 'ZZITZTWYB2L',
    'name': 'Yoga Book with Windows',
    'price': 62739.0,
    'img_url': 'https://www3.lenovo.com/medias/lenovo-tablet-yoga-book-400x300-win10.png?context=bWFzdGVyfHJvb3R8MjQ0MDd8aW1hZ2UvcG5nfGhlYS9oOTMvOTQ0ODE4NTc5MDQ5NC5wbmd8NzY2YzZkNTcwOGUxMGE1MDE2MzQzNzQxZjU0YzY1ZmNhYTFmZWIyZDM4NDQyMjU1MjkyZTczNDRhODMxZWYzMw',
    'url': 'https://www3.lenovo.com/jp/ja/notebooks/yoga/yoga-book/Yoga-Book-with-Windows/p/ZZITZTWYB2L',
    'spliter': 'notebooks',
    'brand': 'yoga',
    'series': 'yoga-book',
    'date': '2018-05-27',
    'description': '<strong>10.1型 2in1タブレット</strong><ul><li>Windows 10 Home 64搭載</li><li>長時間バッテリー駆動</li><li>LTE対応モデルをラインアップ</li></ul>'
}];

export default data_test;